### ISSUE TITLE
CocoaPods Base Configuration

### ISSUE THREAD

**Issue by theneverstill** [blakgeek/cordova-plugin-cocoapod-support#1]
I'm running into a problem where CocoaPods throws the following warning/error after installing some pods (via a plugin's pod requirements):

`[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target '<project name>' to 'Pods/Target Support Files/Pods-<project name>/Pods-<project name>.debug.xcconfig' or include the 'Pods/Target Support Files/Pods-<project name>/Pods-<project name>.debug.xcconfig' in your build configuration ('cordova/build-debug.xcconfig').`

Is there any easy config change to remedy this issue? If so, could you document it?

Thanks!

Lucas

**Comment by theneverstill** [comment]
Ah, I see you're hard coding it to "Pods-Demo". This should be updated to use the application's id.

**Comment by blakgeek** [comment]
Oops.  Good catch.  I'll fix that now.

**Comment by blakgeek** [comment]
This has been fixed in the latest release v1.1.1.  Give it a shot and let me know if you have anymore issues.

**Comment by theneverstill** [comment]
That's the ticket - thanks!
