### ISSUE TITLE
Error: Command failed: pod update

### ISSUE THREAD

**Issue by shashankfire55555** [blakgeek/cordova-plugin-cocoapod-support#3]
I am trying to include the pod 'Charts', '~> 2.2' in my project which is actual in Swift, using **cordova plugin cordova-plugin-cocoapod-support**(id="cordova-plugin-cocoapod-support" version="1.0.2"), still not able to create the iOS project without errors, I added cordova plugin cordova-plugin-add-swift-support also but facing same error. Please help me

**Comment by blakgeek** [comment]
@shashankfire55555 Have you tried the latest version (>1.2.5) of the plugin?  It should have fixed your issue.  

If you're still having issues.  Please add a gist with the output of the following command.
```
ionic build ios --verbose
```

**Comment by blakgeek** [comment]
Fixed in version 1.2.5
